# -*- coding: utf-8 -*-
"""python class7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a9ZpZveUI7_Boqd5RN753-lwjkUU4PfX
"""

import datetime

import datetime
current = datetime.datetime.now()
print(current)

print(current.year)
print(current.strftime("%A"))
print(current.strftime("%B"))
print(current.strftime("%D"))
print(current.strftime("%T"))

import datetime
data = datetime.datetime.now()
print(data)

today = datetime.datetime.now()
print(today)

print(today.year)
print(today.strftime("%A"))
print(today.strftime("%B"))
print(today.strftime("%D"))
print(today.strftime("%T"))

dates = datetime.datetime(2019 ,9, 20)
print(dates)

dates = datetime.datetime(2020 , 10 , 19)
print(dates)
print(today.strftime("%B"))
print(today.strftime("%G"))
print(today.strftime("%X"))

import datetime
x = datetime.datetime.now()
print(x)
print(today.strftime("%C"))
print(today.strftime("%c"))
print(today.strftime("%U"))
print(today.strftime("%Z"))

# maths format working

data = (15,20,25,12,14,35)
data1 = min(15,20,25,12,14,35)
data2 = max(15,20,25,12,14,35)

print(data1)
print(data2)

x = min(3, 25, 35)
y = max(5, 15, 45)

print(x)
print(y)

data = abs(-15)
print(data)

data = abs(-7.25)
print(data)

# power work
data = pow(4,3)
print(data)

data = pow(3,4)
print(data)

import math
x = math.sqrt(361)
print(x)

import math
data = math.sqrt(625)
print(data)

import math
x = math.ceil(2.8) # which number is greater then 2.8.
y = math.floor(2.8) # any one number but less than 2.8 but both number is int fields.

print(x)
print(y)

x = math.pi
print(x)

# json format with json dump format

import json

data = '{"name":"sachin" , "age":"25" , "location":"Delhi", "work":"Web developments"}'

data1 = json.loads(data)
print(data1["location"])
print(data1["name"])
print(data1["age"])
print(data1["work"])

# json dumping used

import json
data = {
    "name": "amit",
    "work": "web developments",
    "age" : "45"
}
data1 = json.dumps(data)
print(data1)

import json
data1 = {
    "name": "amit",
    "work": "web developments",
    "age" : 45,
    "married": True, # boolen fields used
    "child":("deepak","ronda"),
    "House": "Rented",
    "Wife": "Housewife",
    "childage":[
        {"deepak":15},
        {"ronda":12}
    ]
}

family = json.dumps(data1)
print(family)

import json
data1 = {
    "name": "amit",
    "work": "web developments",
    "age" : 45,
    "married": True, # boolen fields used
    "child":("deepak","ronda"),
    "House": "Rented",
    "Wife": "Housewife",
    "childage":[
        {"deepak":15},
        {"ronda":12}
    ]
}

family = json.dumps(data1,indent=2)
print(family)

import json
data1 = {
    "name": "amit",
    "work": "web developments",
    "age" : 45,
    "married": True, # boolen fields used
    "child":("deepak","ronda"),
    "House": "Rented",
    "Wife": "Housewife",
    "childage":[
        {"deepak":15},
        {"ronda":12}
    ]
}

family = json.dumps(data1,indent=4,separators=(". ", " = "),sort_keys=True)
print(family)

import camelcase

c = camelcase.CamelCase()

txt = "hello world"

print(c.hump(txt))



username = input("Enter username:")
print("Username is: " + username)

price = 79.67
txt = "The price is {:.2f} dollars"
print(txt.format(price))

quantity = 3
itemno = 567
price = 49
myorder = "I want {} pieces of item number {} for {:.2f} dollars."
print(myorder.format(quantity, itemno, price))

data = open("datascinec.csv", "x")

import os
os.remove("datascinec.csv")

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(2)

x = np.random.normal(3, 1, 100)
y = np.random.normal(150, 40, 100) / x

plt.scatter(x, y)
plt.show()

train_x = x[:80]
train_y = y[:80]

test_x = x[80:]
test_y = y[80:]

plt.scatter(train_x, train_y)
plt.show()

plt.scatter(test_x, test_y)
plt.show()

# Compiler in python

print("Welcome to Ekon education Sector")

A = "Data science"
B = "Online Class"
C = "By Jai"
print(A,B,C)

# Request Module

import requests
data =requests.get("https://mysandesh.in/vietjet-offers-rs-9-flights-for-indian-travellers/")
print(data.text)

import math
x = math.degrees(95) # which number is greater then 2.8.
y = math.acosh(2.8) # any one number but less than 2.8 but both number is int fields.

print(x)
print(y)

# how Remove duplicate in List

datalist = ["D","C","d","A","a","D","X","Z","T"]
newlist = list(dict.fromkeys(datalist))
print(newlist)

def my_function(data):
  return list(dict.fromkeys(data))

mylist = my_function(["D","C","d","A","a","a","D","X","Z","T"])

print(mylist)

# Reverse to Sting funcation

data = "welcome to data science online class"[::-1]
print(data)

data = "welcome to data science online class"[::-2]
print(data)

data = "welcome to data science online class"[::-5]
print(data)

def funcation(x):
  return x[::-1]
data = "welcome to data science online class"[::-1]
print(data)

def funcation(x):
  return x[::-2]
data = "welcome to data science online class"[::-2]
print(data)

def funcation(x):
  return x[::-3]
data = "welcome to data science online class"[::-3]
print(data)

#maths add two or more number

x = 5
y = 10
sum = x + y
print(sum)

x = input("Type a number: ")
y = input("Type another number: ")

sum = int(x) + int(y)

print("The sum is: ", sum)

x = input("Type a number: ")
y = input("Type a number: ")
z = input("Type you another number: ")

sum = int(x) + int(y) + int(z)

print("The sum is: ", sum)

x = input("Type a number: ")
y = input("Type a number: ")
z = input("Type you another number: ")

multi = int(x) * int(y) * int(z)

print("The sum is: ", multi)

x = input("Type a number: ")
y = input("Type a number: ")
z = input("Type you another number: ")

sub = int(x) - int(y) - int(z)

print("The sum is: ", sub)

x = input("Type a number: ")
y = input("Type a number: ")
z = input("Type you another number: ")

div = int(x) / int(y) / int(z)

print("The sum is: ", div)

x = input("Type a number: ")
y = input("Type a number: ")
z = input("Type you another number: ")

pow = int(x) ** int(y) ** int(z)

print("The sum is: ", pow)

